version: "3"
services:
  edge-service:
    build:
      context: edge-service
    image: alexsimons/sample-edge-service:1.0.0
    depends_on:
      - compute-app-one
      - compute-app-two
    ports:
      - 80:80
      - 443:443
  compute-app-one:
    build:
      context: compute-app-one
    image: alexsimons/compute-app-one:1.0.0
    volumes:
      - ./compute-app-one:/app
    environment:
      - NODE_ENV=production
      - PORT=8909
  compute-app-two:
    build:
      context: compute-app-two
    image: alexsimons/compute-app-two:1.0.0
    volumes:
      - ./compute-app-one:/app
    environment:
      - NODE_ENV=production
      - PORT=8910